// Generated by scripts/build.ts from plugins/artifact-design/src/allow-drafts.ts. Edit the source and run `bun run build`.

// plugins/artifact-design/src/allow-drafts.ts
import { lstatSync as lstatSync2, readFileSync } from "node:fs";
import { basename as basename2, dirname as dirname2, isAbsolute as isAbsolute2, join as join3 } from "node:path";

// plugins/artifact-design/src/drafts.ts
import { lstatSync, mkdirSync, mkdtempSync, readdirSync, rmdirSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
var uid = process.getuid?.();
var DRAFTS_ROOT = join(tmpdir(), uid === undefined ? "artifact-drafts" : `artifact-drafts-${uid}`);
function draftsRootIsOwn() {
  const info = lstatSync(DRAFTS_ROOT, { throwIfNoEntry: false });
  return !!info && info.isDirectory() && (uid === undefined || info.uid === uid);
}

// plugins/artifact-design/src/paths.ts
import { realpathSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, isAbsolute, join as join2, relative, resolve, sep } from "node:path";
function resolvePath(path) {
  const absolute = resolve(expandUser(path));
  try {
    return realpathSync.native(absolute);
  } catch {
    const parent = dirname(absolute);
    return parent === absolute ? absolute : join2(resolvePath(parent), basename(absolute));
  }
}
function expandUser(path) {
  return path === "~" || path.startsWith("~/") || path.startsWith("~\\") ? homedir() + path.slice(1) : path;
}
function partsBelow(folder, path) {
  const rel = relative(folder, path);
  if (!rel || rel === ".." || rel.startsWith(".." + sep) || isAbsolute(rel))
    return null;
  return rel.split(sep);
}

// plugins/artifact-design/src/allow-drafts.ts
function draftsTarget(event) {
  if (!["Write", "Edit", "MultiEdit"].includes(event.tool_name))
    return false;
  const path = event.tool_input?.file_path;
  if (typeof path !== "string" || !isAbsolute2(path) || !draftsRootIsOwn())
    return false;
  const target = join3(resolvePath(dirname2(path)), basename2(path));
  return partsBelow(resolvePath(DRAFTS_ROOT), target) !== null && !lstatSync2(target, { throwIfNoEntry: false })?.isSymbolicLink();
}
var allowed = false;
try {
  allowed = draftsTarget(JSON.parse(readFileSync(0, "utf8")));
} catch {
  allowed = false;
}
if (allowed) {
  console.log(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "allow",
      permissionDecisionReason: "a page draft in the artifact server's private drafts folder"
    }
  }));
}
