// Bundle each plugin's TypeScript entry points into one standalone file for Node, committed beside
// the plugin files that run it, so installing a plugin needs no npm install. Run with `bun run build`;
// CI fails when a committed bundle differs from what this builds.

import { relative, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");

const bundles: { entry: string; out: string }[] = [
  { entry: "plugins/artifact-design/src/server.ts", out: "plugins/artifact-design/mcp/server.mjs" },
  {
    entry: "plugins/artifact-design/src/publish-cli.ts",
    out: "plugins/artifact-design/skills/artifact-design/scripts/publish.mjs",
  },
  { entry: "plugins/artifact-design/src/allow-drafts.ts", out: "plugins/artifact-design/hooks/allow-drafts.mjs" },
];

for (const { entry, out } of bundles) {
  const result = await Bun.build({
    entrypoints: [resolve(root, entry)],
    target: "node",
    format: "esm",
    banner: `// Generated by scripts/build.ts from ${entry}. Edit the source and run \`bun run build\`.`,
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    process.exit(1);
  }
  const [output] = result.outputs;
  await Bun.write(resolve(root, out), await output!.text());
  console.log(`${relative(root, resolve(root, out))}  ${(output!.size / 1024).toFixed(0)} KB`);
}
